no change     /home1/04637/mdl2665/anaconda3/condabin/conda
no change     /home1/04637/mdl2665/anaconda3/bin/conda
no change     /home1/04637/mdl2665/anaconda3/bin/conda-env
no change     /home1/04637/mdl2665/anaconda3/bin/activate
no change     /home1/04637/mdl2665/anaconda3/bin/deactivate
no change     /home1/04637/mdl2665/anaconda3/etc/profile.d/conda.sh
no change     /home1/04637/mdl2665/anaconda3/etc/fish/conf.d/conda.fish
no change     /home1/04637/mdl2665/anaconda3/shell/condabin/Conda.psm1
no change     /home1/04637/mdl2665/anaconda3/shell/condabin/conda-hook.ps1
no change     /home1/04637/mdl2665/anaconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /home1/04637/mdl2665/anaconda3/etc/profile.d/conda.csh
no change     /home1/04637/mdl2665/.bashrc
No action taken.

     active environment : fenicsx-env
    active env location : /home1/04637/mdl2665/anaconda3/envs/fenicsx-env
            shell level : 2
       user config file : /home1/04637/mdl2665/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home1/04637/mdl2665/anaconda3  (writable)
      conda av data dir : /home1/04637/mdl2665/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home1/04637/mdl2665/anaconda3/pkgs
                          /home1/04637/mdl2665/.conda/pkgs
       envs directories : /home1/04637/mdl2665/anaconda3/envs
                          /home1/04637/mdl2665/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/4.18.0-305.12.1.el8_4.x86_64 rocky/8.4 glibc/2.28
                UID:GID : 839365:819760
             netrc file : None
           offline mode : False

TACC:  Starting up job 506159 
TACC:  Starting parallel tasks... 
nt 4000
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 506159 ON c312-014 CANCELLED AT 2022-10-17T15:45:43 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 506159.0 ON c312-014 CANCELLED AT 2022-10-17T15:45:43 DUE TO TIME LIMIT ***
[125]PETSC ERROR: ------------------------------------------------------------------------
[125]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[125]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[125]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind
[125]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple MacOS to find memory corruption errors
[125]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[125]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 125
[126]PETSC ERROR: ------------------------------------------------------------------------
[126]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[126]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[126]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind
[126]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple MacOS to find memory corruption errors
[126]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[126]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 126
